# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Corda Interop App Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_github_packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Generate github.properties (on pull_request)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "Using ${GITHUB_ACTOR} user."
        echo "username=${GITHUB_ACTOR}" >> github.properties
        echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.properties
        echo "url=https://maven.pkg.github.com/${GITHUB_ACTOR}/weaver-dlt-interoperability" >> github.properties
        cat github.properties
      working-directory: core/network/corda-interop-app
      
    - name: Generate github.properties (else)
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "Using ${GITHUB_ACTOR} user."
        echo "username=${GITHUB_ACTOR}" >> github.properties
        echo "password=${{ secrets.GITHUB_TOKEN }}" >> github.properties
        echo "url=https://maven.pkg.github.com/hyperledger-labs/weaver-dlt-interoperability" >> github.properties
        cat github.properties
      working-directory: core/network/corda-interop-app
      
    - name: Build Corda Interop App (Github Packages)
      run: make build
      working-directory: core/network/corda-interop-app
      
    - name: Run Tests (Github Packages)
      run: make test
      working-directory: core/network/corda-interop-app
      
    - name: Delete github.properties
      run: rm github.properties
      working-directory: core/network/corda-interop-app
      
  test_local:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build Protos (Local)
      run: make build
      working-directory: common/protos-java-kt
      
    - name: Build Corda Interop App (Local)
      run: make build-local
      working-directory: core/network/corda-interop-app
      
    - name: Run Tests (Local)
      run: make test
      working-directory: core/network/corda-interop-app
