name: Fabric Interop CC and Sample Chaincode Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_interopcc_github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/contracts/interop
      
    - name: Test
      run: go test -v ./...
      working-directory: core/network/fabric-interop-cc/contracts/interop
      
  test_interopcc_local:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Local Setup
      run: |
        mv go.mod go.mod.bkp
        cp go.mod.local go.mod
        cp -r ../../../../../common/protos-go ./protos-go
        cp -r ../../libs/assetexchange ./assetexchange
        rm go.sum
        go mod tidy
      working-directory: core/network/fabric-interop-cc/contracts/interop
        
    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/contracts/interop
      
    - name: Test
      run: go test -v ./...
      working-directory: core/network/fabric-interop-cc/contracts/interop
      
  test_assetmgmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/interfaces/asset-mgmt
      
    - name: Test
      run: go test -v ./...
      working-directory: core/network/fabric-interop-cc/interfaces/asset-mgmt
      
  test_simpleasset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      working-directory: samples/fabric/simpleasset
      
    - name: Test
      run: go test -v ./...
      working-directory: samples/fabric/simpleasset
      
  test_simpleasset_local:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Setup
      run: |
        GOMODCACHE=`go env GOMODCACHE`
        echo "GO MOD Path: ${GOMODCACHE}"
        go mod download github.com/hyperledger-labs/weaver-dlt-interoperability/core/network/fabric-interop-cc/interfaces/asset-mgmt
        chmod +wr -R ${GOMODCACHE}
        rm -rf ${GOMODCACHE}/github.com/hyperledger-labs/weaver-dlt-interoperability/core/network/fabric-interop-cc/interfaces/asset-mgmt*/*
        cp -r ../../../core/network/fabric-interop-cc/interfaces/asset-mgmt/* ${GOMODCACHE}/github.com/hyperledger-labs/weaver-dlt-interoperability/core/network/fabric-interop-cc/interfaces/asset-mgmt*/
        ls -lh ${GOMODCACHE}/github.com/hyperledger-labs/weaver-dlt-interoperability/core/network/fabric-interop-cc/interfaces/asset-mgmt*
      working-directory: samples/fabric/simpleasset

    - name: Build
      run: go build -v ./...
      working-directory: samples/fabric/simpleasset
      
    - name: Test
      run: go test -v ./...
      working-directory: samples/fabric/simpleasset

